const SalesRetail = [
	"Sales Representatives",
	"Inside Sales",
	"Outside Sales",
	"Technical Sales",
	"Sales Engineers",
	"Sales Management",
	"Retail Sales",
	"Account Management",
	"Business Development",
	"Retail Outlet Management",
	"Supermarket Management",
	"Department Store Management",
	"Hypermarket Management",
];

const Marketing = [
	"Merchandising",
	"Merchandisers",
	"Brand Ambassadors",
	"Influencers",
	"Social Media Marketers",
	"Social Media Marketing Management",
	"Digital Marketing",
	"Digital Marketing Analysts",
	"SEO/SEM and E-commerce",
	"Marketing Analyst",
	"Market Research Analysts",
	"Content Writers",
	"Graphic Designers",
	"Advertising",
	"Brand Management",
	"Promotions Management",
	"Marketing Representatives",
	"Corporate Advertising Management",
	"Product Marketing Managers",
	"Event Marketers",
];

const MediaCommunicationsWriting = [
	"Content Management",
	"Communication Specialists",
	"Communication Management",
	"Public Relations",
	"Technical writing",
	"Blog Writing",
	"Screenwriting",
	"Editing and Editors",
	"Copywriting",
	"Newspaper Publishing",
	"Magazine Publishing",
	"Broadcast Journalism",
	"Photojournalism",
	"Wire Services",
	"Book Publishing",
	"Reporter/Correspondents",
	"Photojournalists",
	"Investigative Journalists",
	"Editorial Cartoonists",
	"Columnists",
	"Editorial Writers",
	"Copy Editors/Proofreaders",
	"Publishers",
	"Fact Checkers",
	"Producers",
	"News Anchors",
	"Script Writers",
	"News Writers",
	"Foreign Language specialists/Translators/Transcribers/Interpreters",
];

const CustomerService = [
	"Call Centre Agents/Reps",
	"Call Centre Management",
	"Customer Service Representatives",
	"Multilingual Customer Service",
	"Client Relations",
	"Customer Service Management",
	"Front Desk Agents",
	"Help Desk Agents",
	"Hostess",
	"Customer Success Management",
];

const ArtFashionDesign = [
	"Graphic design",
	"Fashion design",
	"Art directorship",
	"Floral design",
	"Sculptor",
	"Interior design",
	"Cartoonist",
	"Photography",
	"Illustrator",
	"Special effects artistry",
	"Animation",
	"Videography",
	"Web Designers",
];

const Entertainment = [
	"Film editing",
	"Music composer",
	"Choreography",
	"Actors",
	"Musicians ",
	"Singers",
	"Models",
	"Dancers",
	"Creative Directorship",
];

const ITProgramming = [
	"Cloud Computing Specialists",
	"Computer Network Specialists",
	"Computer Support Specialist",
	"Database Administrators",
	"Information Technology Analysts",
	"Information Security Specialist",
	"Software/Application Developers",
	"Software Engineering",
	"Web Developers",
	"ERP Developers",
	"Solution Architects",
	"System Administrator",
	"Operations Research Analysis",
	"Project Management - Technology",
];

const DataScience = [
	"Data analyst",
	"Business Analyst",
	"Marketing Analyst",
	"Data Architect",
	"Quantitative Analyst",
	"Statistician",
];

const OperationsGeneralManagement = [
	"Operations Management",
	"Operations Improvement",
	"Business Processes Reengineering",
	"Resource Management",
	"Cost Management",
	"Project Management",
	"Strategic Management",
];
const Manufacturing = [
	"Line supervision & Management",
	"Manufacturing Management",
	"Production Planning",
	"Production Management",
	"Quality Assurance",
	"Quality Assurance Management",
	"Safety",
	"Safety, Health (OSHA) & Environment Management",
	"Factory Management",
	"Continuous Improvement",
];
const SupplyChainTransportLogistics = [
	"Procurement Specialists",
	"Buyers",
	"Technical Sourcing Specialists",
	"Procurement Management",
	"Logistics Coordination",
	"Supply Chain Coordination",
	"Supply Chain Coordination",
	"Supply Chain Coordination",
	"Transport Planning",
	"Store Keeping",
	"Warehouse Clerks",
	"Warehouse Management",
	"Distribution Management",
	"Distribution Centre Management",
	"Inventory Management",
	"Routing/Scheduling",
	"Demand Planning",
	"Supply Chain Analyst",
	"Supply Chain Management",
	"Clearing & Forwarding",
	"Freight forwarding",
];
const EngineeringDesignInstallationsOperationsMaintenance = [
	"Water Engineer",
	"Environmental Engineer",
	"Mechanical Engineer",
	"Mechanical Engineer - Design",
	"Mechanical Engineer - Installation",
	"Mechanical Engineer - Maintenance",
	"Mechanical Engineer - Building Services",
	"Chemical Engineer",
	"Process Engineer",
	"Petroleum Engineer",
	"Electrical Engineer",
	"Electrical Engineer - Design ",
	"Electrical Engineer - Installation",
	"Electrical Engineer - Maintenance",
	"Electrical Engineer - Building Services",
	"Electronic Engineer",
	"Mechatronics Engineer",
	"Automotive Engineer - Design",
	"Automotive Engineer - Maintenance",
	"Aerospace Engineer - Design",
	"Aerospace Engineer - Maintenance",
	"Project Management - Design & Installations",
];
const EngineeringConstructionPlanning = [
	"Civil Engineer",
	"Structural Engineer",
	"Geotechnical Engineer",
	"Construction Manager",
	"Quantity Survey",
	"Land Survey",
	"Construction management",
	"Architecture",
	"Landscape architecture",
	"Town planning",
	"Drafting",
	"GIS",
	"Construction inspector",
	"Cost estimator",
	"Construction Safety Management",
	"Project Manager - Engineering & Construction",
];
const EnergyMining = [
	"Geological Engineer",
	"Geoscientist",
	"Nuclear Engineers",
	"Mining Engineer",
	"Mine Safety Engineer",
	"Mine Safety Management",
	"Mineral and Rock Research and Science",
	"Mining Consultant",
	"Open Pit Mining Management",
	"Planning Engineer (Surface and Underground)",
	"Process Mining Digital Engineer",
	"Project Engineer",
	"Tech Specialist Mining Systems",
	"Underground Mining Commissioning Specialist",
	"Surface Mining Supervision",
];
const ScienceLabProfessionals = [
	"Analytical chemist",
	"Animal technician",
	"Biomedical engineer",
	"Biomedical scientist",
	"Clinical psychologist",
	"Clinical research associate",
	"Clothing/textile technologist",
	"Colour technologist",
	"Food technologist",
	"Forensic scientist",
	"Medicinal chemist",
	"Metallurgist",
	"Plant breeder/geneticist",
	"Product/process development scientist",
	"Research scientist ",
	"Scientific laboratory technician",
	"Teaching laboratory technician",
	"Toxicologist",
	"Water quality scientist",
	"Phlebotomists",
	"Blood Bank Specialists",
	"Chemistry Technician",
	"Hematologist",
	"Microbiologist",
	"Molecular Diagnostics Specialist",
	"Cytologist",
	"Histologist",
	"Pathologist",
	"Lab Management",
];
const FinanceAccountingAuditing = [
	"Forensic Accountant",
	"Real Estate Appraiser",
	"Tax Accountant",
	"Accounting Clerk",
	"Accounts Payable/Receivable Clerk",
	"Accounting Information System Specialist",
	"Actuarial Accountant/Insurance Accountant",
	"Bookkeeping",
	"Budget Analyst",
	"Capital Accountant",
	"Comptroller/Financial Controller",
	"Cost Accountant",
	"Environmental Accountant/Sustainability Measurement",
	"Payroll Accountant",
	"Business Valuation Analyst",
	"Certified Financial Planner",
	"Financial Analyst",
	"Tax Consultant",
	"Business Analyst",
	"Investment Analyst ",
	"Internal Auditor",
	"External Auditor",
	"Tax Auditor",
	"Forensic Auditor",
	"Life actuary",
	"General Insurance Actuary",
	"Treasury",
];
const BankingInvestingManagement = [
	"Bank  Teller",
	"Bank Marketing",
	"Branch Management",
	"Financial Analyst",
	"Personal Banker",
	"Loan Officer",
	"Credit Analyst",
	"Credit Administration",
	"Debt Recovery",
	"Relationship Management",
	"Asset Management",
	"Equities Trading",
	"Fixed Income Analyst",
	"Foreign Exchange Trader",
	"Wealth Management",
	"Equity Analyst",
	"Investment Banker",
	"Portfolio Management",
	"Internal Auditors",
	"Audit Management",
	"Compliance - Banking",
];
const OfficeAdmin = [
	"Office Administration",
	"Executive assistant",
	"Office assistant",
	"Receptionist",
	"Office management",
	"Cashier",
	"Data Entry Clerk",
	"Junior Clerk",
	"Senior Clerk",
	"General Clerk",
];
const RestaurantHospitality = [
	"Dietitian",
	"Sous Chef",
	"Head Chef",
	"Executive Chef",
	"Restaurant Management",
	"Hotel General Management",
	"Event Planning",
];
const Security = ["Private Security Contractor", "Private Investigator"];
const HRTraining = [
	"Compensation &  Benefits",
	"Training & Development",
	"Recruitment & Placement",
	"Human Resources Information System (HRIS) Analysts",
	"Employee Assistance",
	"Employee Relations",
	"Labour Law Compliance",
];
const CoachingMotivation = [
	"Life coaching",
	"Career coaching",
	"Sports Coaching",
	"Business/executive coaching",
	"Wellness coaching",
	"Leadership coaching",
	"Team coaching",
	"Educational coaching",
	"Motivational Speaking",
];
const SocialSciencesResearchQualitativeAssessors = [
	"Psychologist",
	"Market research",
	"Economist",
	"Sociologist",
	"Geographers",
	"Anthropologist",
	"Archeologist",
	"Historians",
	"Political scientist",
	"Survey Researchers",
	"Environmental Impact Assessment Auditors/Experts",
	"Monitoring & Evaluation Experts",
	"Public Health Experts/Auditors",
	"Directorate of Occupational Safety & Health Services (DOSHS) Experts/Auditors",
	"Community Social Workers",
	"Community Development",
];
const AgricultureForestryAnimalCare = [
	"Agricultural Engineer",
	"Agricultural Food Scientist",
	"Agronomist",
	"Aquatic Ecologist",
	"Arborist",
	"Beekeeper",
	"Botanist",
	"Conservationist",
	"Fisheries Biologist",
	"Fishery Management",
	"Forest Health Specialist",
	"Horticulturist",
	"Plant Biologist",
	"Plant Ecologist",
	"Soil And Plant Scientist",
	"Soil Engineer",
	"Water Conservationist",
	"Water Quality Specialist",
	"Livestock production management",
	"Animal nutritionist",
	"Veterinarian",
	"Animal scientist",
	"Animal geneticist",
	"Grower",
	"Crop Management",
	"Ranch Management",
	"Farm management",
	"Wildlife Consultant",
	"Wildlife Management",
	"Wildlife Officer",
	"Wildlife Inspector",
	"Wetlands Biologist",
];
const Legal = [
	"Lawyer",
	"Paralegal",
	"Legal Secretary",
	"Legal Assistant",
	"Compliance Specialist",
	"Conflicts Analyst",
	"Litigation Support Professional",
	"E-Discovery Professional",
	"Document Coder",
	"Judge",
	"Magistrate",
	"Prosecutor",
	"Law Clerk",
	"Mediator",
	"Forensic Scientist",
	"Legal Videographer",
	"Accident Reconstructionist",
	"Law Firm Administration",
	"Contract Administration",
	"International Law",
];
const HealthcarePharmacy = [
	"Physician (ER doctors, surgeons, hospitalists)",
	"Nurse (CRNA, RN, LPN/LVN, CNS)",
	"Clinical Officers",
	"Techs (Radiology Tech, Ultrasound Tech, Surgical Tech)",
	"Physiotherapist",
	"Radiation Therapist",
	"Medical Assistants",
	"Pharmacists",
	"Medical Technologist & Medical Laboratory Technologist",
	"Dietitian",
	"Patient Attendants",
	"Retail Pharmacist",
	"Clinical Pharmacist",
	"Nuclear Pharmacist.",
	"Home Infusion and Chemotherapist",
	"Immunization Specialists",
];
const Education = [
	"Kindergarten Teacher",
	"Primary School Teacher",
	"Secondary School Teacher",
	"School Vice Principal",
	"School Principal",
	"Tutor",
	"Librarian",
	"College Lecturer",
	"University Lecturer",
	"University Assistant Professor",
	"University Professor",
	"Vice-Chancellor",
	"Chancellor",
	"Education Policy and Research",
	"Adult Education",
	"Curriculum Design",
	"Educational Consultant",
	"Instructional Designer",
	"School Counseling",
	"Standardized Test Development",
	"Textbook Author",
];
const RealEstate = [
	"Real Estate Investment",
	"Real Estate Agent",
	"Real Estate Broker",
	"Property Management",
	"Property valuation",
	"Land Valuation",
];
const Insurance = [
	"Claims administration",
	"Insurance field inspection",
	"Insurance investigation",
	"Accident and Police Liaison",
	"Claims Examination",
	"Claims Adjustment",
	"Insurance Appraisal",
	"Insurance Broker",
	"Loss control consultant",
	"Actuary",
	"Risk Management",
	"Insurance Underwriting",
	"Valuation",
	"Motor Vehicle Valuation/Assessment",
];
const AviationTravelTourism = [
	"Airline and Commercial Pilot",
	"Airline and Commercial Co-Pilot",
	"Air Traffic Controller",
	"Aircraft Maintenance Engineer",
	"Air Ticketing Staff",
	"Flight Steward/Stewardess",
	"Flight Attendant",
	"Aerospace Engineer",
	"Aviation Management",
	"Quality Control (Aviation)",
	"Flight Test Engineer",
	"Avionics Engineer",
	"Ground Handling Operations",
	"Cargo Operations",
	"Aircraft Technician",
	"Aviation Medicine",
	"Travel Agent",
	"Travel Management",
	"Tourism Management",
	"Tour Management",
	"Tour Operator",
	"Leisure Activity Coordination",
];
const GovernmentGovernmentRelationsInternationalRelationsPublicAdministration =
	[
		"Government Relations Experts",
		"International Relations Experts",
		"Political Analysts",
		"Policy Analysts",
		"Political Consultants",
		"Elected official (city council, mayor, governor, etc.)",
		"City management",
		"Lobbyist",
		"Legislative assistants",
		"Military member (Army, Navy, Marine Corps, Air Force, Coast Guard)",
		"National Police",
		"Foreign and consular service",
		"Diplomatic Affairs",
		"Diplomats and Diplomatic Agents",
		"Planner",
		"Census clerk",
		"Federal aid coordinator",
		"Tax examiner",
		"Internal revenue agent or investigator",
		"Auditor",
		"Bank examiner",
		"Election Management",
		"Cargo or border inspectors",
		"Child support management",
		"Court administration",
		"Court Prosecutors",
		"City, county or court clerks",
		"National Security",
		"Revenue and taxation",
		"Public management and administration",
		"Intelligence specialists",
		"International benefits analysts",
		"Foreign Language specialists/Translators/Transcribers/Interpreters",
		"Public relations specialists",
		"Economic analysts",
		"International policy analysts",
		"Regulatory Affairs Management",
		"International Lawyers",
	];
const BusinessExecutives = [
	"CEOs, Managing Directors, Presidents and Organizational Leadership",
	"COO and Leadership in Operations",
	"CFO and Leadership in Finance",
	"CTO and  Leadership in Technology",
	"CHRO and Leadership in HR",
	"CMO and Leadership in Sales, Marketing and Commercial aspects of business",
	"Other Chiefs, Vice Presidents and Senior Leadership ",
	"Provide dialogue box to populate",
];
const Other = [];

const Speciality = {
	"Sales & Retail": SalesRetail,
	Marketing,
	"Media, Communications & Writing": MediaCommunicationsWriting,
	"Customer Service": CustomerService,
	"Art, Fashion & Design": ArtFashionDesign,
	Entertainment,
	"IT & Programming": ITProgramming,
	"Data Science": DataScience,
	"Operations & General Management": OperationsGeneralManagement,
	Manufacturing,
	"Supply Chain, Transport & Logistics": SupplyChainTransportLogistics,
	"Engineering - Design, Installations, Operations & Maintenance":
		EngineeringDesignInstallationsOperationsMaintenance,
	"Engineering, Construction & Planning": EngineeringConstructionPlanning,
	"Energy & Mining": EnergyMining,
	"Science & Lab Professionals": ScienceLabProfessionals,
	"Finance, Accounting & Auditing": FinanceAccountingAuditing,
	"Banking & Investing Management": BankingInvestingManagement,
	"Office & Admin": OfficeAdmin,
	"Restaurant & Hospitality": RestaurantHospitality,
	Security,
	"HR & Training": HRTraining,
	"Coaching & Motivation": CoachingMotivation,
	"Social Sciences, Research and Qualitative Assessors":
		SocialSciencesResearchQualitativeAssessors,
	"Agriculture, Forestry and Animal Care": AgricultureForestryAnimalCare,
	Legal,
	"Healthcare and Pharmacy": HealthcarePharmacy,
	Education,
	"Real Estate": RealEstate,
	Insurance,
	"Aviation, Travel & Tourism": AviationTravelTourism,
	"Government, Government Relations, International Relations & Public Administration":
		GovernmentGovernmentRelationsInternationalRelationsPublicAdministration,
	"Business Executives": BusinessExecutives,
	Other,
};

export { Speciality };
