const employerChoice = [
	"Accountants",
	"Airlines",
	"Alternative Dispute Resolution",
	"Alternative Medicine",
	"Animation",
	"Apparel & Fashion",
	"Architecture & Planning",
	"Arts & Crafts",
	"Automotive",
	"Aerospace",
	"Banking",
	"Biotechnology",
	"Broadcasting",
	"Building Materials & Equipment",
	"Business Supplies and Equipment",
	"Capital Markets",
	"Chemical industry",
	"Civil Servants/Public Officials",
	"Civil Engineering",
	"Commercial Real Estate",
	"Computer & Network Security",
	"Computer Games",
	"Computer Hardware",
	"Computer Networking",
	"Computer Software",
	"Construction",
	"Consumer Electronics",
	"Consumer Goods",
	"Consumer Services",
	"Cosmetics",
	"Dairy",
	"Defense and Space",
	"Design",
	"E-Learning",
	"Education Management",
	"Electrical & Electrical Manufacturing",
	"Entertainment",
	"Environmental Services",
	"Events Services",
	"Executive Office",
	"Facilities Services",
	"Farming",
	"Financial Services",
	"Fine Art",
	"Fishery",
	"Food & Beverages",
	"Food Production",
	"Fundraising",
	"Furniture",
	"Casinos / Gambling",
	"Glass, Ceramic & Concrete",
	"Government Administration",
	"Government Relations",
	"Graphic Design",
	"Health, Wellness & Fitness",
	"Higher Education",
	"Hospital & Health Care",
	"Hospitality",
	"Human Resources",
	"Import & Export",
	"Individual & Family Services",
	"Industrial Automation",
	"Information Services",
	"Insurance",
	"International Affairs",
	"International Trade and Development",
	"Internet",
	"Investment Banking",
	"Investment Management",
	"Judiciary",
	"Law Enforcement",
	"Law Practice",
	"Legal Services",
	"Legislative Office",
	"Leisure, Travel & Tourism",
	"Libraries",
	"Logistics & Supply Chain",
	"Luxury Goods & Jewelry",
	"Machinery",
	"Management Consulting",
	"Maritime",
	"Market Research",
	"Advertising",
	"Mechanical or Industrial Engineering",
	"Media Production",
	"Medical Device",
	"Medical Practice",
	"Mental Health Care",
	"Military",
	"Mining & Metals",
	"Motion Pictures & Film",
	"Museum & Institutions",
	"Music",
	"Nanotechnology",
	"Newspapers",
	"Non-profit Organization Management",
	"Oil & Energy",
	"Online Media",
	"Outsoucing/Offshoring",
	"Package/Freight Delivery",
	"packaging & Containers",
	"Paper & Forest Products",
	"Performing Arts",
	"Pharmaceuticals",
	"Philanthropy",
	"Plastics",
	"Political Organization",
	"Primary/Secondary Education",
	"Printing",
	"Professional Training & Coaching",
	"Program Development",
	"Public Policy",
	"Public Relations & Communications",
	"Public Safety",
	"Publishing",
	"Railroad Manufacturing",
	"Ranching",
	"Real Estate",
	"Recreation Facilities & Services",
	"Religious institutions",
	"Renewables & Environment",
	"Research",
	"Restaurants",
	"Retail",
	"Security & Investigations",
	"Semiconductors",
	"Shipbuilding",
	"Sporting Goods",
	"Sports",
	"Staffing & Recruiting",
	"Supermarkets",
	"Telecommunications",
	"Textiles",
	"Think Tanks",
	"Tobacco",
	"Transport & Localization",
	"Transport/Trucking/Railroad",
	"Utilities",
	"Veterinary",
	"Warehousing",
	"Wholesale",
	"Beer, Wine & Liquor",
	"Wireless",
	"Writing & Editing",
	"Other",
	"Advertising/Public Relations",
	"Aerospace, Defense Contractors",
	"Agribusiness",
	"Agricultural Services & Products",
	"Agriculture",
	"Agriculture and Agribusiness",
	"Air Transport",
	"Air Transport Unions",
	"Alcoholic Beverages",
	"Alternative Energy Production & Services",
	"Arms",
	"Attorneys/Law Firms",
	"Auto Manufacturers",
	"Banking, Mortgage",
	"Banks, Commercial",
	"Banks, Savings & Loans",
	"Bars & Restaurants",
	"Books, Magazines & Newspapers",
	"Broadcasters, Radio/TV",
	"Builders/General Contractors",
	"Builders/Residential",
	"Building Trade Unions",
	"Business Associations",
	"Business Services",
	"Cable & Satellite TV Production & Distribution",
	"Car Dealers",
	"Car Manufacturers",
	"Cattle Ranchers/Livestock",
	"Chemical & Related Manufacturing",
	"Chiropractors",
	"Clergy & Religious Organizations",
	"Clothing Manufacturing",
	"Coal Mining",
	"Colleges",
	"Colleges, Universities & Schools",
	"Commercial Banks",
	"Commercial TV & Radio Stations",
	"Communications Industry",
	"Communications/Electronics",
	"Computer industry",
	"Construction Services",
	"Courier Services",
	"Creative",
	"Credit Unions",
	"Crop Production & Basic Processing",
	"Cultural industry",
	"Defense",
	"Defense Electronics",
	"Dentists",
	"Doctors & Other Health Professionals",
	"Drug Manufacturers",
	"Education",
	"Electric power industry",
	"Electric Utilities",
	"Electronics",
	"Electronics, Defense Contractors",
	"Energy",
	"Energy & Natural Resources",
	"Entertainment industry",
	"Environment",
	"Fashion",
	"Finance",
	"Finance / Credit Companies",
	"Finance, Insurance & Real Estate",
	"Financial services industry",
	"Floral",
	"Food industry",
	"Food Processing & Sales",
	"Food Products Manufacturing",
	"Food Stores",
	"Forestry & Forest Products",
	"Foundations, Philanthropists & Non-Profits",
	"Funeral Services",
	"Gambling industry",
	"Garbage Collection",
	"Gas & Oil",
	"General Contractors",
	"Government",
	"Government Employee Unions",
	"Gun Control",
	"Health",
	"Health Professionals",
	"Health Services",
	"Healthcare industry",
	"Hedge Funds",
	"Home Builders",
	"Hospitality industry",
	"Hospitals & Nursing Homes",
	"Hotels, Motels & Tourism",
	"HR Services",
	"Human Rights",
	"Industrial Unions",
	"Information Technology",
	"Insurance industry",
	"Lawyers / Law Firms",
	"Leisure industry",
	"Liquor, Wine & Beer",
	"Livestock",
	"Lobbyists",
	"Lodging / Tourism",
	"Logging, Timber & Paper Mills",
	"Manufacturing",
	"Manufacturing (FMCG)",
	"Manufacturing & Distributing",
	"Manufacturing Misc",
	"Marine Industry",
	"Marine Transport",
	"Mass media",
	"Meat processing & products",
	"Medical Supplies",
	"Microfinance",
	"Miscellaneous Services",
	"Mortgage Bankers & Brokers",
	"Motion Picture Production & Distribution",
	"Music industry",
	"Music Production",
	"Natural Gas Pipelines",
	"News media",
	"Newspaper, Magazine & Book Publishing",
	"Non-profits, Foundations & Philanthropists",
	"Nurses",
	"Nursing Homes/Hospitals",
	"Nutritional & Dietary Supplements",
	"Oil & Gas",
	"Petroleum industry",
	"Pharmaceutical",
	"Pharmaceutical Manufacturing",
	"Pharmaceuticals / Health Products",
	"Phone Companies",
	"Physicians & Other Health Professionals",
	"Postal Unions",
	"Poultry & Eggs",
	"Power Utilities",
	"Printing & Publishing",
	"Private Equity & Investment Firms",
	"Professional services",
	"Professional Sports, Sports Arenas & Related Equipment & Services",
	"Public Employees",
	"Public Sector Unions",
	"Publishing & Printing",
	"Pulp and paper industry",
	"Radio/TV Stations",
	"Rail",
	"Railroads",
	"Real estate industry",
	"Record Companies/Singers",
	"Recorded Music & Music Production",
	"Recreation / Live Entertainment",
	"Recruitment",
	"Religious Organizations/Clergy",
	"Residential Construction",
	"Restaurants & Drinking Establishments",
	"Retail Sales",
	"SACCO",
	"Savings & Loans",
	"Schools/Education",
	"Sea Transport",
	"Securities & Investment",
	"Security",
	"Ship Industry",
	"Shipbuilding industry",
	"Software industry",
	"Special Trade Contractors",
	"Sport industry",
	"Sports, Professional",
	"Steel industry",
	"Steel Production",
	"Stock Brokers/Investment Industry",
	"Student Loan Companies",
	"Sugar Industry",
	"Teachers Unions",
	"Telecom Services & Equipment",
	"Telecommunication Services",
	"Telephone Utilities",
	"Textile industry",
	"Timber, Logging & Paper Mills",
	"Tobacco Industry",
	"Transport industry",
	"Transportation",
	"Transportation Unions",
	"TV / Movies / Music",
	"TV Production",
	"Unions",
	"Universities",
	"Universities, Colleges & Schools",
	"Utility",
	"Vegetables & Fruits",
	"Venture Capital",
	"Video game industry",
	"Waste Management",
	"Water & Sanitation",
	"Wine, Beer & Liquor",
];

const candidatesChoice = ["Professional", "General/Technical workers"];

export { employerChoice, candidatesChoice };
